name: Build

on:
  push: branches:[matblg/pipeline-fix-db]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Wait for MongoDB to start
        run: |
          echo "Waiting for MongoDB to become available..."
          for i in {1..15}; do
            nc -z localhost 27017 && echo "MongoDB is up!" && break
            echo "Still waiting..."
            sleep 2
          done

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: backend
